services:
  aross-stations-db:
    image: "postgis/postgis:16-3.4-alpine"

    ports:
      # TODO: Don't expose in prod
      - "5432:5432"
    environment:
      POSTGRES_DB: "aross"
      POSTGRES_USER: "aross"
      POSTGRES_PASSWORD: null
    volumes:
      - "./_data:/var/lib/postgresql/data"
    logging:
      options:
        max-size: "20m"
        max-file: "5"

  aross-stations-db-admin-ui:
    image: "adminer"
    ports:
      - "80:8080"
    restart: "unless-stopped"
    logging:
      options:
        max-size: "20m"
        max-file: "5"
