x-common: &common
  logging:
    options:
      max-size: "20m"
      max-file: "5"

# TODO: Use a tag!
x-image: &image "nsidc/aross-stations-db"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.api.address=:8000
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=scott.lewis@colorado.edu
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --providers.docker=true
      - --log.level=INFO
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/letsencrypt
    labels:
      - "traefik.enable=true"
    restart: unless-stopped

  ui:
    container_name: "aross-stations-ui"
    depends_on: ["api"]
    image: "nsidc/aross-stations-ui:latest"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.aross-ui.rule=Host(`localhost`) && PathPrefix(`/apps/aross-stations`)"
      - "traefik.http.routers.aross-ui.entrypoints=websecure"
      - "traefik.http.routers.aross-ui.tls=true"
      - "traefik.http.routers.aross-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.aross-ui.middlewares=aross-ui"
      - "traefik.http.routers.aross-ui.service=aross-ui"
      - "traefik.http.middlewares.aross-ui.stripprefix.prefixes=/apps/aross-stations"
      - "traefik.http.services.aross-ui.loadbalancer.server.port=80"

      # Production domain (nsidc.org)
      # - "traefik.http.routers.aross-prod.rule=Host(`nsidc.org`) && PathPrefix(`/apps/aross`)"
      # - "traefik.http.routers.aross-prod.entrypoints=websecure"
      # - "traefik.http.routers.aross-prod.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.aross-prod.middlewares=strip-aross-path"

    restart: unless-stopped
    profiles: ["ui"]


  api:
    container_name: "aross-stations-api"
    depends_on: ["db"]
    image: *image
    <<: *common

    entrypoint: "fastapi"
    command: ["run", "--host", "0.0.0.0", "./src/aross_stations_db/api"]

    labels:
      - "traefik.enable=true"

      # local
      - "traefik.http.routers.aross-api.rule=Host(`localhost`) && PathPrefix(`/api/aross-stations`)"
      - "traefik.http.routers.aross-api.entrypoints=websecure"
      - "traefik.http.routers.aross-api.tls=true"
      - "traefik.http.routers.aross-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.aross-api.middlewares=aross-api"
      - "traefik.http.routers.aross-api.service=aross-api"
      - "traefik.http.middlewares.aross-api.stripprefix.prefixes=/api/aross-stations"
      - "traefik.http.services.aross-api.loadbalancer.server.port=8000"

    environment:
      AROSS_DB_CONNSTR: null


  db:
    container_name: "aross-stations-db"
    image: "postgis/postgis:16-3.4-alpine"
    <<: *common

    environment:
      POSTGRES_DB: "aross"
      POSTGRES_USER: "aross"
      POSTGRES_PASSWORD: null
    ports:
      - "5432:5432"
    volumes:
      - "./_data:/var/lib/postgresql/data"


  admin:
    container_name: "aross-stations-admin"
    depends_on: ["db"]
    image: "adminer"
    <<: *common

    ports:
      - "8080:8080"
    restart: "unless-stopped"


  cli:
    container_name: "aross-stations-cli"
    depends_on: ["db"]
    image: *image
    <<: *common

    volumes:
      - "${AROSS_DATA_BASEDIR}:/data"
    environment:
      AROSS_DATA_BASEDIR: "/data"
      AROSS_DB_CONNSTR: null
    # Prevents this "service" from running with `docker compose up`.
    # Instead, it's intended to be used like `docker compose run cli --help`.
    profiles: ["_"]


  jupyterlab:
    container_name: "aross-stations-jupyterlab"
    depends_on: ["api"]
    image: *image
    <<: *common

    entrypoint: "jupyter"
    command: ["lab", "--allow-root", "--ip=0.0.0.0"]
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: "${POSTGRES_PASSWORD}"
