
x-dev-common: &dev-common
  image: "nsidc/aross-stations-db:dev"
  build: "."
  volumes:
    - "${PWD}:/app"


services:
  ui:
    <<: *dev-common

  api:
    <<: *dev-common
    command: ["dev", "--host", "0.0.0.0", "./src/aross_stations_db/api"]

  cli:
    <<: *dev-common
