x-common: &common
  logging:
    options:
      max-size: "20m"
      max-file: "5"

services:
  api:
    container_name: "aross-stations-api"
    depends_on: ["db"]
    image: "nsidc/aross-stations-db"  # TODO: Real tag!
    <<: *common

    entrypoint: "fastapi"
    command: ["dev", "--host", "0.0.0.0", "./src/aross_stations_db/api"]
    ports:
      - "8000:8000"


  db:
    container_name: "aross-stations-db"
    image: "postgis/postgis:16-3.4-alpine"
    <<: *common

    environment:
      POSTGRES_DB: "aross"
      POSTGRES_USER: "aross"
      POSTGRES_PASSWORD: null
    volumes:
      - "./_data:/var/lib/postgresql/data"


  admin:
    container_name: "aross-stations-admin"
    depends_on: ["db"]
    image: "adminer"
    <<: *common

    ports:
      - "8080:8080"
    restart: "unless-stopped"


  cli:
    container_name: "aross-stations-cli"
    depends_on: ["db"]
    image: "nsidc/aross-stations-db"  # TODO: Real tag!
    <<: *common

    volumes:
      - "${AROSS_DATA_BASEDIR}:/data"
    environment:
      AROSS_DATA_BASEDIR: "/data"
    profiles:
      # Prevents this "service" from running with `docker compose up`.
      # Instead, it's intended to be used like `docker compose run cli --help`.
      - "_"
