x-common: &common
  logging:
    options:
      max-size: "20m"
      max-file: "5"

# TODO: Use a tag!
x-image: &image "nsidc/aross-stations-db"

services:
  ui:
    container_name: "aross-stations-ui"
    depends_on: ["api"]
    image: "nsidc/aross-stations-ui:v0.1.0"
    ports:
      - "80:80"
      - "443:443"
    profiles: ["ui"]


  api:
    container_name: "aross-stations-api"
    depends_on: ["db"]
    image: *image
    <<: *common

    entrypoint: "fastapi"
    command: ["run", "--host", "0.0.0.0", "./src/aross_stations_db/api"]
    ports:
      - "8000:8000"
    environment:
      AROSS_DB_CONNSTR: null


  db:
    container_name: "aross-stations-db"
    image: "postgis/postgis:16-3.4-alpine"
    <<: *common

    environment:
      POSTGRES_DB: "aross"
      POSTGRES_USER: "aross"
      POSTGRES_PASSWORD: null
    volumes:
      - "./_data:/var/lib/postgresql/data"


  admin:
    container_name: "aross-stations-admin"
    depends_on: ["db"]
    image: "adminer"
    <<: *common

    ports:
      - "8080:8080"
    restart: "unless-stopped"


  cli:
    container_name: "aross-stations-cli"
    depends_on: ["db"]
    image: *image
    <<: *common

    volumes:
      - "${AROSS_DATA_BASEDIR}:/data"
    environment:
      AROSS_DATA_BASEDIR: "/data"
      AROSS_DB_CONNSTR: null
    # Prevents this "service" from running with `docker compose up`.
    # Instead, it's intended to be used like `docker compose run cli --help`.
    profiles: ["_"]


  jupyterlab:
    container_name: "aross-stations-jupyterlab"
    depends_on: ["api"]
    image: *image
    <<: *common

    entrypoint: "jupyter"
    command: ["lab", "--allow-root", "--ip=0.0.0.0"]
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: "${POSTGRES_PASSWORD}"
