
x-dev-common: &dev-common
  image: "nsidc/aross-stations-db:dev"
  build: "."
  volumes:
    - "${PWD}:/app"


services:
  api:
    <<: *dev-common
    command: ["dev", "--host", "0.0.0.0", "./src/aross_stations_db/api"]
    # ports:
    #   - "8000:8000"
    # NOTE: In place of the above command, which uses the image's default
    # `fastapi` entrypoint, you can run the container with no server (using
    # "sleep" instead):
    #
    # entrypoint: "sleep"
    # command: ["9999999"]
    #
    # ... then, you can connect to the container for debugging, e.g.  by
    # placing a breakpoint in code then interactively running the server
    # process:
    #     docker compose exec api fastapi dev --host 0.0.0.0 ./src/aross_stations_db/api

  cli:
    <<: *dev-common
  
  jupyterlab:
    <<: *dev-common
