services:
  api:
    image: "nsidc/aross-stations-db:dev"
    build: "."
    volumes:
      - "${PWD}:/app"

  cli:
    image: "nsidc/aross-stations-db:dev"
    build: "."  # TODO: Dev compose
    volumes:
      - "${PWD}:/app"
